# Generated by Django 5.2.8 on 2025-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_getquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getquote',
            name='details',
            field=models.TextField(),
        ),
    ]
